### ISSUE TITLE
Hex logo

### ISSUE THREAD

**Issue by anyaferguson** [nhs-r-community/NHSRdatasets#102]
As part of creating a packages page for the NHSRcommunity website https://github.com/nhs-r-community/nhs-r-community/issues/219, I've designed a hex sticker for this package. Will do a PR shortly with the code and logo, but happy to take feedback and tweak the design as desired.

**Comment by Lextuga007** [comment]
Looks great! Linking this comment to the PR but keeping it open to add this to the README and pkgdown.

**Comment by anyaferguson** [comment]
@all-contributors please add @anyaferguson for design
