### ISSUE TITLE
Names of A and E datasets

### ISSUE THREAD

**Issue by ChrisBeeley** [nhs-r-community/NHSRdatasets#14]
I've just written some code to scrape the API of the organisation data service so I can put the names of the Trusts into the A & E data so it looks a bit more engaging than having those weird codes (for my forthcoming Shiny training :-) )

Want me to left join it to the original data and make a pull request to save others the job? Or is the sparsity of the dataset part of the point? Excuse my ignorance, I really never work with national data like this.

I'm sure you'll see this but this is aimed at you @tomjemmett 

Edit: And maybe postcodes and Lat/ Long too? I'm adding them in as well

**Comment by chrismainey** [comment]
Maybe worth adding as separate data set as a look up take. Then can write a vignette featuring? With the ODS API stuff, we had dinner similar scripts but didn't publish them. Wonder if an NHSRtools package is helpful? API stuff, common calculations, certain plot types, NHS colours palette?

**Comment by tomjemmett** [comment]
I’m not too against adding the names of organisations to the dataset, but I would favour having a package that can somehow pull in reference data: either by API calls, or have some function that on first call downloads the ods data then returns a data frame. I’m not sure though what license the ods is released under...

**Comment by ChrisBeeley** [comment]
I can't seem to see a licence for the ODS API. I've emailed them to ask them.

Postcodes are released under the OGL http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/.

The problem with postcodes is the file size is rather large. If I'm reading your two comments together correctly you would like to see the A & E data left alone and a separate package produced which would allow one to easily look up names, postcodes, and perhaps other data too, and that this package would also have more stuff added to it over time that would have generally useful NHS type code in it.

Something like that?

**Comment by tomjemmett** [comment]
closing this as it's going to be handled in #23 instead
