### ISSUE TITLE
Investigate update function for ONSMortality

### ISSUE THREAD

**Issue by chrismainey** [nhs-r-community/NHSRdatasets#18]
Include a function to update the ONS mortality data in whichever way seems most appropriate.

**Comment by chrismainey** [comment]
Same as #23

**Comment by tomjemmett** [comment]
Don’t think this is same as #23, that’s to get ods data, this was about the ons mortality files! 🙂

**Comment by chrismainey** [comment]
Oh, good shout.  Crossed wires with some HED work too.  Quite right

**Comment by tomjemmett** [comment]
@Lextuga007 is this going to be handled in [monstr](https://github.com/HFAnalyticsLab/monstR)?

**Comment by Lextuga007** [comment]
Yes, good point. It might be an idea to merge the two in a vignette. One of the columns come through as a character (for week number) so will need some coding to make it an integer so that would fit a vignette nicely. I'll update an issue I have on monstR about this. Thanks.

**Comment by Lextuga007** [comment]
I've had a go with monstr https://lextuga007.github.io/PhilosopherAnalyst/posts/2021-02-08-using-monstr-package/ but it didn't look like it was up to date when I did this blog. I'll have a look again. Might be best to write up a vignette and include this as an additional step.
