### ISSUE TITLE
use tidyverse style guide for naming

### ISSUE THREAD

**Issue by tomjemmett** [nhs-r-community/NHSRdatasets#20]
see [tidyverse style guide](https://style.tidyverse.org/syntax.html): the recommendation is to use snake case for naming where possible.

It's probably not a good idea to do this to published datasets (e.g. LOSModel/ae_attendances), but we could employ it with the as yet unpublished ONS Deaths data.

Changes required: convert column names to snake case, rename dataset ons_mortality

**Comment by Lextuga007** [comment]
I hadn't realised they use snake case! Thanks, I will amend accordingly.

**Comment by chrismainey** [comment]
Good idea.  Go for it.
