### ISSUE TITLE
ONS Mortality data set Categories need tidying

### ISSUE THREAD

**Issue by Lextuga007** [nhs-r-community/NHSRdatasets#22]
The category labels have changed over time and could do with some merging where possible. This should be a separate column to retain the original ONS labelling. In finding this out I used this code to create a unique column that could be ordered (Names):
 
t <- Mortality %>% 
  mutate(year = year(Date)) %>%
  unite("Names", c("Category", "year"), remove = FALSE) %>% 
  filter(!is.na(Counts)) %>% 
  select(Category,
         year,
         Names) %>% 
  group_by(Category,
           year, 
           Names) %>% 
  slice(1) %>% 
  arrange(Names)

Category possibly needs to be two separate columns as this has been merged together.

**Comment by chrismainey** [comment]
Updated this, hope that's ok.  Update your fork form master, or pull mater directly to get latest.  Would you mind checking it is ok, and renaming the category variables as required?  Package builds and passed R CMD check at this point.

**Comment by Lextuga007** [comment]
I've realised I need to do a bit of tidying of these column names. I've sorted out the years 2010 to 2015 and once finished I'll update the roxygen file (and finish off the vignette).
