### ISSUE TITLE
Column name in data file is mis-typed

### ISSUE THREAD

**Issue by DavidNphe** [nhs-r-community/NHSRdatasets#26]
In the following data file https://github.com/nhs-r-community/NHSRdatasets/blob/master/data/ons_mortality.rda the name of "category_1" is mis-typed as "cateogry_1".

This looks like a very useful project. Thanks for sharing it.

**Comment by tomjemmett** [comment]
many thanks @DavidNphe! great catch! If you have any ideas of other useful datasets to add please raise an issue 😉
