### ISSUE TITLE
Add licence

### ISSUE THREAD

**Issue by chrismainey** [nhs-r-community/NHSRdatasets#3]
Waiting NHS-R community decision on licence.  Currently only one artificial dataset in rep, built and published by CM, so unlicensed is fine for now.

**Comment by tomjemmett** [comment]
If we utilise any data sets that are released under [OGL v3.0](http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/) then we would need to attribute to the source, but I don't think then that this would be contradictory to it being released under CC0.

**Comment by chrismainey** [comment]
Added as a merge

**Comment by chrismainey** [comment]
Added as a merge
