### ISSUE TITLE
Need a vignette for the synthetic NEWS dataset

### ISSUE THREAD

**Issue by chrismainey** [nhs-r-community/NHSRdatasets#36]
We would normally require this to show users what you can do with it, as it's a training package. Do you have one to hand @StatsGary ?

**Comment by StatsGary** [comment]
Chris. I will get on it tomorrow. I am running a massive model on my machine and don't think it has the bandwidth 😂

**Comment by StatsGary** [comment]
Keep the pull request open and I can send back over. Cheers

**Comment by chrismainey** [comment]
Sorry, need a new PR, as I've changed branches over to main instead of master.  Made a hash of it so it won't automatically do it.

**Comment by StatsGary** [comment]
No worries

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by StatsGary** [comment]
@tomjemmett and @chrismainey: https://web.archive.org/web/20200128111444/https://www.datadictionary.nhs.uk/data_dictionary/attributes/a/acc/accident_and_emergency_department_type_de.asp

**Comment by chrismainey** [comment]
resolved in b6fd5c019d9a370a27bded2b537b2eb45c3f44eb
