### ISSUE TITLE
Invalid link in A&E

### ISSUE THREAD

**Issue by chrismainey** [nhs-r-community/NHSRdatasets#37]
Invalid link found in cran win-builder checks for https://www.datadictionary.nhs.uk/data_dictionary/attributes/a/acc/accident_and_emergency_department_type_de.asp

do you mind tying up @tomjemmett ?

**Comment by StatsGary** [comment]
Yes it has. The day I released my package lol 🤣

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tomjemmett** [comment]
@StatsGary it looks like the [current website](https://datadictionary.nhs.uk/attributes/retired/accident_and_emergency_department_type.html) doesn't list the old codes. Think it is worth linking to [archive.org](https://web.archive.org/web/20200128111444/https://www.datadictionary.nhs.uk/data_dictionary/attributes/a/acc/accident_and_emergency_department_type_de.asp) instead?

**Comment by StatsGary** [comment]
Solid plan that.

Gary Hutson
________________________________

**Comment by chrismainey** [comment]
Just that link, then we can go for release to CRAN.  Shall we find archived link?

**Comment by StatsGary** [comment]
@tomjemmett and @chrismainey: https://web.archive.org/web/20200128111444/https://www.datadictionary.nhs.uk/data_dictionary/attributes/a/acc/accident_and_emergency_department_type_de.asp
