### ISSUE TITLE
Change package maintainer

### ISSUE THREAD

**Issue by Lextuga007** [nhs-r-community/NHSRdatasets#56]
As discussed with @chrismainey, change of package maintainer to @Lextuga007.

**Comment by Lextuga007** [comment]
I hadn't noticed this had happened in November! Commit d4ecdbd

**Comment by Lextuga007** [comment]
- [ ] Change @StatsGary to dtc - data contributor (https://stat.ethz.ch/R-manual/R-devel/library/utils/html/person.html) 
- [ ] Change CRE from @chrismainey to @Lextuga007 
- [ ] @chrismainey to inform CRAN of the change

**Comment by chrismainey** [comment]
We need to do a CRAN release to change the maintainer.  This involved moving the version number as a minimum, if we make no other changes.

**Comment by Lextuga007** [comment]
The covid-19 dataset is new but does that make the package too big to go to CRAN now?

**Comment by chrismainey** [comment]
Would need to build it and see.  Would ideally need a vignette written to show it's use.  This is both for pkgdown site and the package vignette.

**Comment by Lextuga007** [comment]
Closing as the DESCRIPTION file has been updated and a release to CRAN would be a separate issue.
