### ISSUE TITLE
Move "data origin" code into a data-raw folder

### ISSUE THREAD

**Issue by francisbarton** [nhs-r-community/NHSRdatasets#65]
As suggested in the [R packages book](https://r-pkgs.org/data.html#sec-data-data-raw).

Instead of under 'Working files'.

Check all code still works to build datasets while we're at it.

**Comment by francisbarton** [comment]
Some initial work on this (for the covid19 dataset) has been done in my fork of this project. A PR will be submitted once issue #69 is resolved.

**Comment by francisbarton** [comment]
Data sourcing and preparation scripts are not currently present for the LOS model, A&E attendances, stranded patient model and synthetics NEWS data.
We really ought to have the code for these processes available if at all possible, for reproducibility reasons.

Some information about the synthetic NEWS data is reconstructable from the vignette.

**Comment by chrismainey** [comment]
Again, I'm not sure you will get these, as the preparation was not the original use case, it was to have a package with small datasets to be used in training.  Although the prep would be a nice tutorial. 
LOS_model was me fiddling with it in Excel until it performed the interaction I wanted it to.  I don't have a script for that I'm afraid, as it's entirely made up.  I think the stranded patient model synthetic news ones have some related blog posts on the old website.  Not sure if still around.
