### ISSUE TITLE
Internal: Restructure ONS mortality data preparation workflow

### ISSUE THREAD

**Issue by francisbarton** [nhs-r-community/NHSRdatasets#69]
Instead of multiple code sections for downloading CSV/XLS files that are then stored within the package directory, we should use functions that read in data directly from the URLs, process the data structures and bind them together without saving intermediate files to disk.

Or amend the workflow entirely to use the [Nomis API](https://www.nomisweb.co.uk/datasets/mortsa).

However, the documentation for this package says that this data is for teaching purposes - I'm not sure if it's just the data itself that is used for this, or whether the data preparation process itself is part of a set of teaching materials.

I'm happy to do the work to amend the workflow for this dataset, if this issue is approved. But it would mean rewriting the current data preparation vignette as well.

**Comment by chrismainey** [comment]
I'm not sure this needs doing to be done, as you pointed out, because the original reason was to give NHS-like data for training.  The was what Zoe used to prepare it, rather than being a workflow for people to follow.  Depends on what you want to do with the package.

**Comment by Lextuga007** [comment]
The vignette I wrote was to explain how I built the dataset but I'm totally in favour of a replacement of that with a reworking using the Nomis API - unless that's another API package?

**Comment by Lextuga007** [comment]
Another idea @francisbarton is to write the rework but as a blog for the NHS-R website Quarto site? I think this package needs simpler examples of how to use the data but the higher level information is still incredibly useful.
